/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.ac.picb.popgenomics.ui;

import cn.ac.picb.popgenomics.api.Configure;
import cn.ac.picb.popgenomics.api.PickFile;
import com.jcraft.jsch.Session;


/**
 *
 * @author young
 */
public class aptCallDialog extends javax.swing.JDialog {

    /**
     * Creates new form aptCallDialog
     */
    public aptCallDialog(MainFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        libTextField = new javax.swing.JTextField();
        chrxTextField = new javax.swing.JTextField();
        chryTextField = new javax.swing.JTextField();
        ssnpTextField = new javax.swing.JTextField();
        sgmTextField = new javax.swing.JTextField();
        rmbTextField = new javax.swing.JTextField();
        cfTextField = new javax.swing.JTextField();
        _aTextField = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        _oTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Lib File:");

        jLabel2.setText("chrX-probes:");

        jLabel3.setText("chrY-probes:");

        jLabel4.setText("special-snps:");

        jLabel5.setText("set-gender-method:");

        jLabel6.setText("read-models-birdseed:");

        jLabel7.setText("-a:");

        jLabel8.setText("cel-files:");

        libTextField.setText("/picb/humpopg2/yangxiong/software/CD_GenomeWideSNP_6_rev3/Full/GenomeWideSNP_6/LibFiles/GenomeWideSNP_6.Full.cdf");
        libTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libTextFieldActionPerformed(evt);
            }
        });

        chrxTextField.setText("/picb/humpopg2/yangxiong/software/CD_GenomeWideSNP_6_rev3/Full/GenomeWideSNP_6/LibFiles/GenomeWideSNP_6.chrXprobes");
        chrxTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chrxTextFieldActionPerformed(evt);
            }
        });

        chryTextField.setText("/picb/humpopg2/yangxiong/software/CD_GenomeWideSNP_6_rev3/Full/GenomeWideSNP_6/LibFiles/GenomeWideSNP_6.chrYprobes");
        chryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chryTextFieldActionPerformed(evt);
            }
        });

        ssnpTextField.setText("/picb/humpopg2/yangxiong/software/CD_GenomeWideSNP_6_rev3/Full/GenomeWideSNP_6/LibFiles/GenomeWideSNP_6.Full.specialSNPs");
        ssnpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnpTextFieldActionPerformed(evt);
            }
        });

        sgmTextField.setText("cn-probe-chrXY-ratio");

        rmbTextField.setText("/picb/humpopg2/yangxiong/software/CD_GenomeWideSNP_6_rev3/Full/GenomeWideSNP_6/LibFiles/GenomeWideSNP_6.birdseed-v2.models");

        cfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfTextFieldActionPerformed(evt);
            }
        });

        _aTextField.setText("birdseed-v2");

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("-o:");

        _oTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _oTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(libTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(chrxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(chryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(ssnpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(sgmTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                            .addComponent(rmbTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(cfTextField)
                            .addComponent(_aTextField)
                            .addComponent(_oTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {exitButton, submitButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(libTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(chrxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(chryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ssnpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sgmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rmbTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(_aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(_oTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(submitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        MainFrame main = (MainFrame)getParent();
        Configure config = main.getConfig();
        Session session = main.getSession();
        String cmd = getCmd(config);
        main.submit(session, cmd);
        dispose();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void libTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libTextFieldActionPerformed
        libTextField.setText(new PickFile().getFile("open", false));
    }//GEN-LAST:event_libTextFieldActionPerformed

    private void chrxTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chrxTextFieldActionPerformed
        chrxTextField.setText(new PickFile().getFile("open", false));
    }//GEN-LAST:event_chrxTextFieldActionPerformed

    private void chryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chryTextFieldActionPerformed
        chryTextField.setText(new PickFile().getFile("open", false));
    }//GEN-LAST:event_chryTextFieldActionPerformed

    private void ssnpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnpTextFieldActionPerformed
        ssnpTextField.setText(new PickFile().getFile("open", false));
    }//GEN-LAST:event_ssnpTextFieldActionPerformed

    private void cfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfTextFieldActionPerformed
        cfTextField.setText(new PickFile().getFile("open", false));
    }//GEN-LAST:event_cfTextFieldActionPerformed

    private void _oTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__oTextFieldActionPerformed
        _oTextField.setText(new PickFile().getFile("open", true));
    }//GEN-LAST:event__oTextFieldActionPerformed

    public String getCmd(Configure config){
        StringBuilder cmd = new StringBuilder();
        cmd.append("cd /picb/humpopg2/XY/chip_data \n");
        cmd.append("/picb/humpopg2/yangxiong/software/x86_64-intel-linux/bin/apt-probeset-genotype ");
        String field;
        field=libTextField.getText().trim();
        cmd.append(" -c ").append(field);
        field=chrxTextField.getText().trim();
        cmd.append(" --chrX-probes ").append(field);
        field=chryTextField.getText().trim();
        cmd.append(" --chrY-probes ").append(field);
        field=ssnpTextField.getText().trim();
        cmd.append(" --special-snps ").append(field);
        field=rmbTextField.getText().trim();
        cmd.append(" --read-models-birdseed ").append(field);
        field=_aTextField.getText().trim();
        cmd.append(" -a ").append(field);
        field=cfTextField.getText().trim();
        cmd.append(" --cel-files ").append(field);
        field=_oTextField.getText().trim();
        cmd.append(" -o ").append(field);
        cmd.append(" & \n");
        System.out.println(cmd.toString());
        return cmd.toString();
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _aTextField;
    private javax.swing.JTextField _oTextField;
    private javax.swing.JTextField cfTextField;
    private javax.swing.JTextField chrxTextField;
    private javax.swing.JTextField chryTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField libTextField;
    private javax.swing.JTextField rmbTextField;
    private javax.swing.JTextField sgmTextField;
    private javax.swing.JTextField ssnpTextField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
