/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.ac.picb.popgenomics.ui;

import cn.ac.picb.popgenomics.api.Configure;
import cn.ac.picb.popgenomics.api.PickFile;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JFileChooser;

/**
 *
 * @author young
 */
public class ConfigForm extends javax.swing.JDialog {

    /**
     * Creates new form ConfigForm
     */
    public ConfigForm(MainFrame main, boolean modal) {
        super(main, modal);
        initComponents();
        initConfig(main);
        this.setLocationRelativeTo(main);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        divReadsTextField = new javax.swing.JTextField();
        bwaTextField = new javax.swing.JTextField();
        samtoolsTextField = new javax.swing.JTextField();
        aorrgTextField = new javax.swing.JTextField();
        markDupTextField = new javax.swing.JTextField();
        gatkTextField = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        configButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuration");

        jLabel1.setText("Reads Dividing Tool:");

        jLabel2.setText("Aligner BWA:");

        jLabel3.setText("SAMTools:");

        jLabel4.setText("AddOrReplaceReadGroups:");

        jLabel5.setText("MarkDuplicates:");

        jLabel6.setText("GenomeAnalysisTK:");

        divReadsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divReadsTextFieldActionPerformed(evt);
            }
        });

        bwaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bwaTextFieldActionPerformed(evt);
            }
        });

        samtoolsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samtoolsTextFieldActionPerformed(evt);
            }
        });

        aorrgTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aorrgTextFieldActionPerformed(evt);
            }
        });

        markDupTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markDupTextFieldActionPerformed(evt);
            }
        });

        gatkTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gatkTextFieldActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        configButton.setText("Config");
        configButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(divReadsTextField)
                            .addComponent(markDupTextField)
                            .addComponent(bwaTextField)
                            .addComponent(samtoolsTextField)
                            .addComponent(aorrgTextField)
                            .addComponent(gatkTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 282, Short.MAX_VALUE)
                        .addComponent(configButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {configButton, exitButton, resetButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(divReadsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bwaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(samtoolsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(aorrgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(markDupTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(gatkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(resetButton)
                    .addComponent(configButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        divReadsTextField.setText("");
        aorrgTextField.setText("");
        bwaTextField.setText("");
        samtoolsTextField.setText("");
        gatkTextField.setText("");
        markDupTextField.setText("");
    }//GEN-LAST:event_resetButtonActionPerformed

    private void configButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configButtonActionPerformed
        if (config == null) {
            config = new Configure();
        }
        String divRead = divReadsTextField.getText().trim();
        String bwa = bwaTextField.getText().trim();
        String samtools = samtoolsTextField.getText().trim();
        String aORRG = aorrgTextField.getText().trim();
        String markDup = markDupTextField.getText().trim();
        String gATK = gatkTextField.getText().trim();
        config.setDivRead(divRead);
        config.setBwa(bwa);
        config.setSamtools(samtools);
        config.setaORRG(aORRG);
        config.setMarkDup(markDup);
        config.setgATK(gATK);
        //System.out.println(this.getParent());
        MainFrame main =(MainFrame)this.getParent();
        //udpate MainFrame configuration
        main.setConfig(config);
        
        //automatically save configurartion to .properties.xml
        try {
            Properties prop = new Properties();
            prop.setProperty("config.divRead", config.getDivRead());
            prop.setProperty("config.bwa", config.getBwa());
            prop.setProperty("config.samtools", config.getSamtools());
            prop.setProperty("config.aORRG", config.getaORRG());
            prop.setProperty("config.markDup", config.getMarkDup());
            prop.setProperty("config.gATK", config.getgATK());

            File propFile = new File(".properties.xml");
            if (!propFile.exists()) {
                propFile.createNewFile();
            }
            FileOutputStream fos = new FileOutputStream(propFile);
            prop.storeToXML(fos, null);
            fos.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        this.dispose();
    }//GEN-LAST:event_configButtonActionPerformed

    private void divReadsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divReadsTextFieldActionPerformed
        divReadsTextField.setText(new PickFile().getFile("open",false));
    }//GEN-LAST:event_divReadsTextFieldActionPerformed

    private void bwaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bwaTextFieldActionPerformed
        bwaTextField.setText(new PickFile().getFile("open",false));
    }//GEN-LAST:event_bwaTextFieldActionPerformed

    private void samtoolsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samtoolsTextFieldActionPerformed
        samtoolsTextField.setText(new PickFile().getFile("open",false));
    }//GEN-LAST:event_samtoolsTextFieldActionPerformed

    private void aorrgTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aorrgTextFieldActionPerformed
        aorrgTextField.setText(new PickFile().getFile("open",false));
    }//GEN-LAST:event_aorrgTextFieldActionPerformed

    private void markDupTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markDupTextFieldActionPerformed
        markDupTextField.setText(new PickFile().getFile("open",false));
    }//GEN-LAST:event_markDupTextFieldActionPerformed

    private void gatkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gatkTextFieldActionPerformed
        gatkTextField.setText(new PickFile().getFile("open",false));
    }//GEN-LAST:event_gatkTextFieldActionPerformed

    public void initConfig(MainFrame main) {
        if (main.getConfig()!=null) {
            this.config = main.getConfig();
            divReadsTextField.setText(config.getDivRead());
            aorrgTextField.setText(config.getaORRG());
            bwaTextField.setText(config.getBwa());
            samtoolsTextField.setText(config.getSamtools());
            gatkTextField.setText(config.getgATK());
            markDupTextField.setText(config.getMarkDup());
        }
    }

    public Configure getConfig() {
        return this.config;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aorrgTextField;
    private javax.swing.JTextField bwaTextField;
    private javax.swing.JButton configButton;
    private javax.swing.JTextField divReadsTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField gatkTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField markDupTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField samtoolsTextField;
    // End of variables declaration//GEN-END:variables
    private Configure config;
}
