/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.ac.picb.popgenomics.ui;

import cn.ac.picb.popgenomics.api.Job;
import cn.ac.picb.popgenomics.api.PickFile;
import com.jcraft.jsch.JSchException;
import com.jcraft.jsch.Session;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author young
 */
public class DivReadsForm extends javax.swing.JDialog {

    /**
     * Creates new form DivReadsForm
     */
    public DivReadsForm(MainFrame main, boolean modal) {
        super(main, modal);
        initComponents();
        this.setLocationRelativeTo(main);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fastqTextField = new javax.swing.JTextField();
        numberTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tardirTextField = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Fastq File:");

        jLabel2.setText("Dividing Number:");

        fastqTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastqTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Target Directory:");

        tardirTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tardirTextFieldActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fastqTextField)
                            .addComponent(numberTextField)
                            .addComponent(tardirTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 236, Short.MAX_VALUE)
                        .addComponent(submitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {exitButton, submitButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fastqTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tardirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(submitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void fastqTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastqTextFieldActionPerformed
        fastqTextField.setText(new PickFile().getFile("open", false));
    }//GEN-LAST:event_fastqTextFieldActionPerformed

    private void tardirTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tardirTextFieldActionPerformed
        tardirTextField.setText(new PickFile().getFile("open", true));
    }//GEN-LAST:event_tardirTextFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String fastq = fastqTextField.getText();
        if (fastq == null || fastq.length() == 0) {
            JOptionPane.showMessageDialog(this, "Input file must be specified", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String tardir = tardirTextField.getText();
        if (tardir == null || tardir.length() == 0) {
            JOptionPane.showMessageDialog(this, "Target directory must be specified", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String number = numberTextField.getText().trim();
        if (number == null || number.length() == 0) {
            JOptionPane.showMessageDialog(this, "Dividing number must be specified", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        MainFrame main = (MainFrame) getParent();
        String program = main.getConfig().getDivRead();
        //read.dividing.pl -f file.fastq -n 10000
        String cmd = new StringBuilder().append(" ").append(program).append(" -f ").append(fastq)
                .append(" -n ").append(number).append(" -o ").append(tardir).append(" & \n").toString();
        System.out.println(cmd);
        //String test= "date; sleep 200; ls \n";
        Session session = main.getSession();
        Job job = new Job(session, cmd);
        try {
            job.submit();
        } catch (JSchException ex) {
            Logger.getLogger(DivReadsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_submitButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField fastqTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField tardirTextField;
    // End of variables declaration//GEN-END:variables
}
