/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.ac.picb.popgenomics.ui;

import cn.ac.picb.popgenomics.api.Configure;
import cn.ac.picb.popgenomics.api.Job;
import cn.ac.picb.popgenomics.api.PickFile;
import com.jcraft.jsch.JSchException;
import com.jcraft.jsch.Session;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author young
 */
public class SampeDialog extends javax.swing.JDialog {

    /**
     * Creates new form AlignDialog
     */
    public SampeDialog(MainFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        refTextField = new javax.swing.JTextField();
        pair1TextField = new javax.swing.JTextField();
        outTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sai2TextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pair2TextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sai1TextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        _nTextField = new javax.swing.JTextField();
        _oTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        _aTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        _NTextField = new javax.swing.JTextField();
        _PCheckBox = new javax.swing.JCheckBox();
        exitButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reads Alignment");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Reference and IO Setting"));

        jLabel1.setText("Reference Index:");

        jLabel2.setText("Querry Reads Pair 1:");

        jLabel3.setText("Output:");

        refTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refTextFieldActionPerformed(evt);
            }
        });

        pair1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pair1TextFieldActionPerformed(evt);
            }
        });

        outTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Sai File Pair 2:");

        sai2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sai2TextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Querry Reads Pair 2:");

        pair2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pair2TextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Sai File Pair 1:");

        sai1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sai1TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pair1TextField)
                    .addComponent(outTextField)
                    .addComponent(refTextField)
                    .addComponent(sai2TextField)
                    .addComponent(pair2TextField)
                    .addComponent(sai1TextField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(refTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pair1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pair2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sai1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sai2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(outTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Parameters Setting"));

        jLabel4.setText("maxHitPaired(-n):");

        jLabel5.setText("maxOcc(-o):");

        _nTextField.setText("3");

        _oTextField.setText("100000");

        jLabel9.setText("maxInsSize(-a):");

        _aTextField.setText("500");

        jLabel10.setText("maxHitDis)-N):");

        _NTextField.setText("10");

        _PCheckBox.setText("Load the Entire FM-index(-P)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_aTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(_nTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_oTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(_NTextField)))
                    .addComponent(_PCheckBox))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(_aTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(_oTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(_nTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(_NTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_PCheckBox)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {exitButton, submitButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(submitButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        MainFrame main = (MainFrame)getParent();
        Configure config = main.getConfig();
        Session session = main.getSession();
        String cmd = getCmd(config);
        try {
            new Job(session,cmd).submit();
        } catch (JSchException ex) {
            Logger.getLogger(SampeDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void pair1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pair1TextFieldActionPerformed
        pair1TextField.setText(new PickFile().getFile("open",false));
    }//GEN-LAST:event_pair1TextFieldActionPerformed

    private void outTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outTextFieldActionPerformed
        outTextField.setText(new PickFile().getFile("open",false));
    }//GEN-LAST:event_outTextFieldActionPerformed

    private void refTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refTextFieldActionPerformed
        refTextField.setText(new PickFile().getFile("open",false));
    }//GEN-LAST:event_refTextFieldActionPerformed

    private void pair2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pair2TextFieldActionPerformed
        pair2TextField.setText(new PickFile().getFile("open",false));
    }//GEN-LAST:event_pair2TextFieldActionPerformed

    private void sai1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sai1TextFieldActionPerformed
        sai1TextField.setText(new PickFile().getFile("open",false));
    }//GEN-LAST:event_sai1TextFieldActionPerformed

    private void sai2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sai2TextFieldActionPerformed
        sai2TextField.setText(new PickFile().getFile("open",false));
    }//GEN-LAST:event_sai2TextFieldActionPerformed

   public String getCmd(Configure config){
       StringBuilder cmd = new StringBuilder();
       String program = config.getBwa();
       cmd.append(program).append(" sampe ");
       
       //check if the default value changed
       String field;
       field = _aTextField.getText().trim();
       if(!field.equals("500")){
           cmd.append(" -n ").append(field);
       }
       field = _oTextField.getText().trim();
       if(!field.equals("100000")){
           cmd.append(" -o ").append(field);
       }
       field = _nTextField.getText().trim();
       if(!field.equals("3")){
           cmd.append(" -n ").append(field);
       }
       field = _NTextField.getText().trim();
       if(!field.equals("10")){
           cmd.append(" -N ").append(field);
       }
       
       if(_PCheckBox.isSelected()){
           cmd.append(" -P ");
       }
       //get the reference index and input output files
       //it should be further extended to validate the input
       field = refTextField.getText().trim();
       cmd.append(" ").append(field);
       field = sai1TextField.getText().trim();
       cmd.append(" ").append(field);
       field = sai2TextField.getText().trim();
       cmd.append(" ").append(field);
       field = pair1TextField.getText().trim();
       cmd.append(" ").append(field);
       field = pair2TextField.getText().trim();
       cmd.append(" ").append(field);
       field = outTextField.getText().trim();
       cmd.append(" ").append(field);
       cmd.append(" & \n");//submit job in background
       
       return cmd.toString();
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _NTextField;
    private javax.swing.JCheckBox _PCheckBox;
    private javax.swing.JTextField _aTextField;
    private javax.swing.JTextField _nTextField;
    private javax.swing.JTextField _oTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField outTextField;
    private javax.swing.JTextField pair1TextField;
    private javax.swing.JTextField pair2TextField;
    private javax.swing.JTextField refTextField;
    private javax.swing.JTextField sai1TextField;
    private javax.swing.JTextField sai2TextField;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
